# MySQL database shared with tomcat containers.
db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: nimda
    MYSQL_DATABASE: example_db
    MYSQL_USER: example_db_user
    MYSQL_PASSWORD: example_db_pass
  volumes:
    - "./db:/docker-entrypoint-initdb.d"
